name: Code Auto-compile Test (lint)

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: |
        chmod +x ./gradlew
        ./gradlew clean
        ./gradlew assembleDebug
        ./gradlew lint
    - name: Upload Compiled APK
      uses: actions/upload-artifact@v1
      with:
          name: arXivPaperReader
          path: ./app/build/outputs/apk/debug/app-debug.apk
    - name: Upload Code-Check Report
      uses: actions/upload-artifact@v1
      with:
        name: LintReport
        path: ./app/build/reports/lint-results.html
